### ISSUE TITLE
Syntax error problem

### ISSUE THREAD

**Issue by Raysultan** [drifter1/compiler#1]
As you said, I did everything and it worked. But when I try to compile the example file, it gives me an Syntax error on line 6. Can you help me?
I think it is because of an initialization of array
![image](https://user-images.githubusercontent.com/15179794/54064316-b813e900-4245-11e9-8466-1d98d5b7765f.png)

**Comment by MonySOEURN** [comment]
you have to use RBRACK before LBRACK in array grammar in parser.y.
